environnementplate_form_homepage:
    path:     /
    defaults: { _controller: EnvironnementplateFormBundle:Default:index }

hello_the_world:
    path:    /hello-world
    defaults: { _controller: EnvironnementplateFormBundle:Advert:index }
